# Generated by Django 5.0.2 on 2024-08-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_tracking', '0002_expensestracking_amount_expensestracking_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensestracking',
            name='expense_type',
            field=models.CharField(choices=[('single', 'Single Payment'), ('monthly', 'Monthly Recurring')], default='single', max_length=10),
        ),
    ]
