# Generated by Django 5.0.2 on 2024-08-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_tracking', '0005_alter_expensestracking_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensestracking',
            name='expense_type',
        ),
    ]
