# Generated by Django 5.0.2 on 2024-03-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_status', '0003_financialstatus_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialstatus',
            name='is_created_in_dashboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalfinancialstatus',
            name='is_created_in_dashboard',
            field=models.BooleanField(default=False),
        ),
    ]
