# Generated by Django 5.0.2 on 2024-03-20 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_status', '0004_financialstatus_is_created_in_dashboard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialstatus',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalfinancialstatus',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
