# Generated by Django 5.0.2 on 2024-03-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='working_hours_per_day',
            field=models.PositiveSmallIntegerField(default=8),
        ),
    ]
