# Generated by Django 5.0.2 on 2024-08-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings_tracking', '0002_earningstracking_amount_earningstracking_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='earningstracking',
            name='amount_type',
            field=models.CharField(choices=[('hour', 'Per Hour'), ('month', 'Per Month')], default='hour', max_length=10),
        ),
    ]
