# Generated by Django 5.0.2 on 2024-08-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings_tracking', '0004_alter_earningstracking_amount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earningstracking',
            name='amount_type',
            field=models.CharField(choices=[('hour', 'Per Hour'), ('month', 'Per Month')], default='hour', max_length=10),
        ),
    ]
