# Generated by Django 5.0.2 on 2024-10-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings_tracking', '0005_alter_earningstracking_amount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earningstracking',
            name='amount_type',
            field=models.CharField(choices=[('single', 'single expense'), ('month', 'per month')], default='single', max_length=10),
        ),
    ]
